<?php

namespace AdminBundle\Repository;

/**
 * AdminEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
