<?php

namespace CompanyBundle\Repository;

/**
 * CompanyEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
