AdminBundle\Entity\AdminEntity:
    type: entity
    table: null
    repositoryClass: AdminBundle\Repository\AdminEntityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
        phone:
            type: string
            length: 255
        password:
            type: string
            length: 255
    lifecycleCallbacks: {  }
