CompanyBundle\Entity\Event:
    type: entity
    table: null
    repositoryClass: CompanyBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        phone:
            type: array
            nullable: true
            unique: true
        address:
            type: string
            length: 255
        code:
            type: string
            length: 255
        city:
            type: string
            length: '60'
        state:
            type: string
            length: '50'
        description:
            type: string
            length: 255
            nullable: true
        category:
            type: array
            nullable: true
    lifecycleCallbacks: {  }
